services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ports:
      - '9200'
    volumes:
      - heryjs-elasticsearch:/usr/share/elasticsearch/data

volumes:
  heryjs-elasticsearch:
