services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: heryjs
      POSTGRES_PASSWORD: heryjs
      POSTGRES_DB: heryjs
    ports:
      - '5432:5432'
    volumes:
      - heryjs-postgres:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    ports:
      - '6479:6379'
    volumes:
      - heryjs-valkey:/data

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - '443:443'
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - heryjs-caddy-data:/data

volumes:
  heryjs-postgres:
  heryjs-valkey:
  heryjs-caddy-data:
