import { existsSync } from 'node:fs';
import * as path from 'node:path';
import { walkFiles } from '../walk';
import type { LintRule, Violation } from '../types';

const ROOTS = ['src/functional', 'examples'];

// Every suffix `hery generate` writes for a resource, keyed by the kebab
// name derived from its own controller. The record loader breaks the
// "kebab + dot-suffix" pattern (a hyphen, not a dot) because it is not a
// facet of the resource so much as a companion file, so it is named
// separately below rather than folded into this list.
const EXPECTED_SUFFIXES = [
  '.service.ts',
  '.policy.ts',
  '.view.ts',
  '.factory.ts',
  '.dto.ts',
  '.module.ts',
  '.spec.ts',
];

function checkResource(controllerFile: string, repoRoot: string): Violation[] {
  const dir = path.dirname(controllerFile);
  const kebabName = path.basename(controllerFile, '.controller.ts');

  // The invariant hery generate maintains for a resource's own root
  // controller. A companion controller like <kebab>.stream.controller.ts
  // fails it, which is the point: `--stream` never writes the nine files this
  // rule would otherwise demand for a resource that was never generated.
  if (kebabName !== path.basename(dir)) {
    return [];
  }

  const relativeDir = path.relative(repoRoot, dir).split(path.sep).join('/');
  const relativeController = path
    .relative(repoRoot, controllerFile)
    .split(path.sep)
    .join('/');

  const missing = [
    ...EXPECTED_SUFFIXES.filter(
      (suffix) => !existsSync(path.join(dir, `${kebabName}${suffix}`)),
    ).map((suffix) => `${kebabName}${suffix}`),
    ...(existsSync(path.join(dir, `${kebabName}-record.loader.ts`))
      ? []
      : [`${kebabName}-record.loader.ts`]),
  ];

  // Anchored on the controller, which exists, rather than on the missing
  // companion file: a violation's hash is read off `violation.file`, and a
  // file that does not exist cannot be hashed to tell "still missing" apart
  // from "state changed since this was grandfathered".
  return missing.map((name) => ({
    rule: 'resource-shape',
    severity: 'minor',
    file: relativeController,
    message: `${relativeDir}/ has a controller but no ${name} -- a resource generated by hery generate ships all of these together`,
  }));
}

export const resourceShapeRule: LintRule = {
  name: 'resource-shape',
  run(repoRoot) {
    return ROOTS.flatMap((root) => {
      const dir = path.join(repoRoot, root);
      return existsSync(dir)
        ? walkFiles(dir, (name) => name.endsWith('.controller.ts'))
        : [];
    }).flatMap((file) => checkResource(file, repoRoot));
  },
};
