import { readFileSync } from 'node:fs';
import * as path from 'node:path';
import * as yaml from 'js-yaml';
import { z } from 'zod';
import { kebabCase } from './naming';

export const permissionPresetSchema = z.enum(['own', 'team', 'all', 'none']);

export const blueprintFieldSchema = z.object({
  name: z.string().regex(/^[a-z][a-zA-Z0-9]*$/),
  type: z.enum(['string', 'int', 'boolean', 'datetime']),
  optional: z.boolean().default(false),
  hidden: z.boolean().default(false),
});

export const blueprintSchema = z.object({
  name: z.string().regex(/^[A-Z][a-zA-Z0-9]*$/),
  fields: z.array(blueprintFieldSchema).default([]),
  permissions: z
    .object({
      view: permissionPresetSchema.default('own'),
      create: permissionPresetSchema.default('own'),
      update: permissionPresetSchema.default('own'),
      delete: permissionPresetSchema.default('own'),
    })
    .default({ view: 'own', create: 'own', update: 'own', delete: 'own' }),
  pagination: z
    .object({
      limits: z.array(z.number().int().positive()).default([10, 15, 20]),
      default: z.number().int().positive().default(15),
    })
    .default({ limits: [10, 15, 20], default: 15 }),
  sorts: z
    .array(z.string().regex(/^[a-z][a-zA-Z0-9]*$/))
    .default(['createdAt']),
  filters: z.array(z.string().regex(/^[a-z][a-zA-Z0-9]*$/)).default([]),
});

export type PermissionPreset = z.infer<typeof permissionPresetSchema>;
export type BlueprintField = z.infer<typeof blueprintFieldSchema>;
export type Blueprint = z.infer<typeof blueprintSchema>;

// Columns the generator owns. A blueprint declaring one of them would put a
// client-writable field on top of a column the framework decides, which is how
// a caller ends up choosing its own owner or team.
const RESERVED_FIELDS = new Set([
  'id',
  'tenantId',
  'ownerId',
  'teamId',
  'createdAt',
  'updatedAt',
  'deletedAt',
]);

function assertNoReservedField(
  blueprint: Blueprint,
  report: (message: string) => void,
): void {
  for (const field of blueprint.fields) {
    if (RESERVED_FIELDS.has(field.name)) {
      report(
        `field "${field.name}" is generated by hery and must not be declared`,
      );
    }
  }
}

// The columns a sort or filter entry may name beyond the blueprint's own
// fields -- every generated column except tenantId, which multi-tenancy
// already applies ahead of anything a caller can request.
const KNOWN_NON_FIELD_SORT_FILTER_TARGETS = new Set([
  'id',
  'createdAt',
  'updatedAt',
  'deletedAt',
  'ownerId',
  'teamId',
]);

/**
 * Both arrays are interpolated unescaped into generated TypeScript and used
 * as raw Prisma `orderBy`/`where` keys, so an entry that names nothing real
 * is not a "no rows" query -- it is a controller that fails to compile, or a
 * 500 on the search route the moment it is called.
 */
function assertSortsAndFiltersAreKnownFields(
  blueprint: Blueprint,
  report: (message: string) => void,
): void {
  const fieldNames = new Set(blueprint.fields.map((field) => field.name));

  for (const [kind, entries] of [
    ['sort', blueprint.sorts],
    ['filter', blueprint.filters],
  ] as const) {
    for (const entry of entries) {
      if (
        !fieldNames.has(entry) &&
        !KNOWN_NON_FIELD_SORT_FILTER_TARGETS.has(entry)
      ) {
        report(`${kind} "${entry}" names no declared field`);
      }
    }
  }
}

/**
 * Accepts either a blueprint name, resolved under `blueprints/`, or a path to a
 * YAML file. A name is the everyday case; a path is what makes a blueprint
 * usable where it makes sense to keep it, next to what it produced.
 */
export function resolveBlueprintPath(root: string, nameOrPath: string): string {
  const looksLikePath =
    /\.ya?ml$/.test(nameOrPath) ||
    nameOrPath.includes('/') ||
    nameOrPath.includes(path.sep);

  return looksLikePath
    ? path.resolve(root, nameOrPath)
    : path.join(root, 'blueprints', `${kebabCase(nameOrPath)}.yaml`);
}

export function loadBlueprint(filePath: string): Blueprint {
  const raw = yaml.load(readFileSync(filePath, 'utf8'));
  const blueprint = blueprintSchema.parse(raw);
  const problems: string[] = [];

  assertNoReservedField(blueprint, (message) => problems.push(message));
  assertSortsAndFiltersAreKnownFields(blueprint, (message) =>
    problems.push(message),
  );

  if (problems.length > 0) {
    throw new Error(
      `Incoherent blueprint ${filePath}:\n${problems.map((problem) => `  - ${problem}`).join('\n')}`,
    );
  }

  return blueprint;
}
